import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('board, snapshots, manual override, reload, filtering and atomic currency change on mobile',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/auth');
  await page.getByRole('button',{name:'הרשמה',exact:true}).click();
  await page.getByLabel('אימייל',{exact:true}).fill(`currency-${Date.now()}@example.test`);
  await page.getByLabel('כינוי',{exact:true}).fill('Currency Tester');
  await page.getByLabel('סיסמה',{exact:true}).fill('Testing123!');
  await page.getByRole('button',{name:'הירשם',exact:true}).click();
  await expect(page).toHaveURL(/\/boards$/);
  await page.getByRole('button',{name:'לוח חדש',exact:true}).click();
  let dialog=page.getByRole('dialog');
  await dialog.getByLabel('שם הלוח',{exact:true}).fill('Serbia currency test');
  await dialog.getByLabel('מטבע הלוח החדש',{exact:true}).selectOption('RSD');
  await dialog.getByRole('button',{name:'צור לוח',exact:true}).click();
  await page.getByText('Serbia currency test',{exact:true}).click();
  await expect(page).toHaveURL(/\/board\//);
  async function add(merchant,amount,currency){
    await page.getByRole('button',{name:'עסקה חדשה',exact:true}).click();
    const form=page.getByRole('dialog');
    await form.getByLabel('שם',{exact:true}).fill('Currency Tester');
    await form.getByLabel('סוג עסקה',{exact:true}).selectOption('cash');
    await form.getByLabel('שם העסק',{exact:true}).fill(merchant);
    await form.getByLabel('סכום',{exact:true}).fill(amount);
    await form.getByLabel('מטבע העסקה',{exact:true}).selectOption(currency);
    await form.getByRole('button',{name:'הוסף עסקה',exact:true}).click();
    await expect(form).not.toBeVisible();
  }
  await add('Cash dinner','1000','RSD');
  await add('Hotel','10','EUR');
  await expect(page.getByTestId('original-totals')).toContainText('EUR');
  await expect(page.locator('main')).toContainText('2,170.00');
  const card=page.locator('div.rounded-xl').filter({has:page.getByText('Hotel',{exact:true})}).last();
  await card.getByRole('button',{name:'ערוך',exact:true}).click();
  dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'הזן שער ידני',exact:true}).click();
  await dialog.getByLabel('שער: 1 EUR = RSD',{exact:true}).fill('120');
  await dialog.getByRole('button',{name:'עדכן עסקה',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  await page.reload();
  await expect(page.locator('main')).toContainText('2,200.00');
  await expect(page.locator('main')).toContainText('ידני');
  await page.getByRole('button',{name:/סינון/}).click();
  await page.getByPlaceholder('הקלד כדי לחפש...').fill('Hotel');
  await expect(page.locator('main')).not.toContainText('2,200.00');
  await expect(page.locator('main')).toContainText('1,200.00');
  await page.getByPlaceholder('הקלד כדי לחפש...').fill('');
  await page.setViewportSize({width:390,height:844});
  await page.locator('summary').filter({hasText:'מטבע הלוח:'}).click();
  await page.getByLabel('מטבע הלוח',{exact:true}).selectOption('USD');
  page.once('dialog',async d=>{expect(d.message()).toContain('שערים ידניים');await d.accept();});
  await page.getByRole('button',{name:'שנה מטבע',exact:true}).click();
  await expect(page.locator('summary')).toContainText('USD');
  await expect(page.locator('main')).toContainText('21.00');
  await expect(page.locator('main')).not.toContainText('ידני');
  await expect(page.locator('main')).toContainText('EUR');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  for (const row of await page.getByTestId('transaction-card').all()) {
    const name = await row.getByTestId('transaction-name').boundingBox();
    const amount = await row.getByTestId('transaction-amount').boundingBox();
    expect(name).not.toBeNull();
    expect(amount).not.toBeNull();
    expect(name.y + name.height <= amount.y || amount.y + amount.height <= name.y ||
      name.x + name.width <= amount.x || amount.x + amount.width <= name.x).toBeTruthy();
  }
  await mkdir('docs/screenshots',{recursive:true});
  await page.screenshot({path:'docs/screenshots/multi-currency-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'עסקה חדשה',exact:true}).click();
  dialog=page.getByRole('dialog');
  await dialog.getByLabel('מטבע העסקה — חיפוש',{exact:true}).fill('Japanese');
  await dialog.getByLabel('מטבע העסקה',{exact:true}).selectOption('JPY');
  expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();
  await page.screenshot({path:'docs/screenshots/multi-currency-form-mobile.png',fullPage:true});
  await dialog.getByRole('button',{name:'סגור',exact:true}).click();
  await page.setViewportSize({width:1280,height:900});
  await page.screenshot({path:'docs/screenshots/multi-currency-desktop.png',fullPage:true});
  expect(errors).toEqual([]);
});
