import test, {after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {initializeTestEnvironment, assertFails, assertSucceeds} from '@firebase/rules-unit-testing';
import {doc, setDoc, updateDoc, deleteDoc, getDoc, collection, query, where, getDocs} from 'firebase/firestore';
import {createHierarchyOperations} from '../functions/hierarchyOperations.mjs';
import {createMoneyOperations} from '../functions/moneyOperations.mjs';
const require=createRequire(new URL('../functions/index.js',import.meta.url));
const admin=require('firebase-admin');
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';
const projectId='demo-nested-boards';
const app=admin.initializeApp({projectId},'hierarchy-integration');
const db=app.firestore(), timestamp=()=>admin.firestore.FieldValue.serverTimestamp();
const hierarchy=createHierarchyOperations({db,timestamp});
let provider='boi', offline=false;
const money=createMoneyOperations({db,timestamp,getRate:async()=>{if(offline)throw Error('offline');return {rate:'3.335',rateDate:'2026-10-07',source:'automatic',provider};}});
const create=async(parentBoardId=null,currency='ILS',uid='owner')=>(await hierarchy.createBoard(uid,{title:'Board',currency,parentBoardId})).id;
const read=async id=>(await db.doc(`boards/${id}`).get()).data();
const rows=async id=>(await db.collection(`boards/${id}/transactions`).get()).docs.map(d=>({id:d.id,...d.data()}));
const save=async(boardId,input={amount:'1.00',currency:'ILS'},uid='owner')=>money.saveTransaction(uid,{boardId,expectedCurrencyRevision:0,input:{name:'Test',essence:'Food',type:'cash',...input}});
const rules=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080,rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});
after(async()=>{await rules.cleanup();await app.delete();});
test('legacy root, root/child creation, several levels, exact child queries, safe move and detach',async()=>{
 const legacy=db.collection('boards').doc();await legacy.set({title:'Legacy',ownerUid:'owner',memberUids:['owner']});
 const a=await create(),b=await create(a),c=await create(b),d=await create(c);
 assert.equal((await read(a)).parentBoardId,null);assert.equal((await read(d)).parentBoardId,c);
 assert.deepEqual((await db.collection('boards').where('parentBoardId','==',a).get()).docs.map(d=>d.id),[b]);
 assert.ok((await hierarchy.listBoardRoots('owner')).boards.some(b=>b.id===legacy.id));
 await hierarchy.reparentBoard('owner',{boardId:b,parentBoardId:legacy.id});
 assert.equal((await read(c)).parentBoardId,b);
 await hierarchy.reparentBoard('owner',{boardId:b,parentBoardId:null});assert.equal((await read(b)).parentBoardId,null);
});
test('rejects self/descendant/missing/foreign parents and malicious client payloads',async()=>{
 const a=await create(),b=await create(a),c=await create(b),foreign=await create(null,'ILS','stranger');
 for(const parentBoardId of [a,b,c,'missing',foreign,{},'',false]) await assert.rejects(hierarchy.reparentBoard('owner',{boardId:a,parentBoardId}));
 await assert.rejects(hierarchy.createBoard('owner',{title:'Bad',parentBoardId:foreign}),{code:'permission-denied'});
 await assert.rejects(hierarchy.reparentBoard('stranger',{boardId:b,parentBoardId:foreign}),{code:'permission-denied'});
 assert.equal((await read(a)).parentBoardId,null);
 await assert.rejects(hierarchy.getHierarchySummary('stranger',{boardId:a}),{code:'permission-denied'});
});
test('concurrent reciprocal reparent attempts cannot create a cycle',async()=>{
 const a=await create(),b=await create();
 const results=await Promise.allSettled([hierarchy.reparentBoard('owner',{boardId:a,parentBoardId:b}),hierarchy.reparentBoard('owner',{boardId:b,parentBoardId:a})]);
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
 assert.ok(!((await read(a)).parentBoardId===b&&(await read(b)).parentBoardId===a));
});
test('malformed cyclic and cross-owner links fail closed, legacy reverse caches are ignored',async()=>{
 const a=await create(),b=await create(a),foreign=await create(null,'ILS','stranger');
 await db.doc(`boards/${a}`).update({parentBoardId:b});
 await assert.rejects(hierarchy.getHierarchySummary('owner',{boardId:a}),/cycle/);
 await assert.rejects(hierarchy.reparentBoard('owner',{boardId:foreign,parentBoardId:a}));
 await db.doc(`boards/${a}`).update({parentBoardId:null,subBoardIds:[foreign]});
 assert.equal((await hierarchy.getHierarchySummary('owner',{boardId:a})).boardCount,2);
 await db.doc(`boards/${foreign}`).update({parentBoardId:a});
 await assert.rejects(hierarchy.getHierarchySummary('owner',{boardId:a}),{code:'permission-denied'});
});
test('sharing cascades atomically, direct members persist through moves, no upward access',async()=>{
 const a=await create(),b=await create(a),c=await create(b),target=await create();
 await db.doc(`boards/${a}/invites/guest`).set({invitedEmailLower:'guest@example.test'});
 await hierarchy.changeMembership('guest',{boardId:a,inviteId:'guest'},'accept','guest@example.test');
 for(const id of [a,b,c])assert.ok((await read(id)).memberUids.includes('guest'));
 await db.doc(`boards/${c}/invites/direct`).set({invitedEmailLower:'guest@example.test'});
 await hierarchy.changeMembership('guest',{boardId:c,inviteId:'direct'},'accept','guest@example.test');
 await hierarchy.reparentBoard('owner',{boardId:b,parentBoardId:target});
 assert.ok(!(await read(b)).memberUids.includes('guest'));assert.ok((await read(c)).memberUids.includes('guest'));
 await assert.rejects(hierarchy.getHierarchySummary('guest',{boardId:b}),{code:'permission-denied'});
 assert.equal((await hierarchy.getHierarchySummary('guest',{boardId:c})).boardCount,1);
 await hierarchy.changeMembership('owner',{boardId:c,memberUid:'guest'},'remove');
 assert.ok(!(await read(c)).memberUids.includes('guest'));
});
test('inherited-only leave retains inherited access; direct invitation identity and expiry enforced',async()=>{
 const a=await create(),b=await create(a);
 await db.doc(`boards/${a}/invites/guest`).set({invitedEmailLower:'guest@example.test'});
 await assert.rejects(hierarchy.changeMembership('attacker',{boardId:a,inviteId:'guest'},'accept','attacker@example.test'));
 await hierarchy.changeMembership('guest',{boardId:a,inviteId:'guest'},'accept','guest@example.test');
 await hierarchy.changeMembership('guest',{boardId:b},'leave');assert.ok((await read(b)).memberUids.includes('guest'));
 await hierarchy.changeMembership('guest',{boardId:a},'leave');assert.ok(!(await read(b)).memberUids.includes('guest'));
 await db.doc(`boards/${a}/invites/expired`).set({invitedEmailLower:'guest@example.test',expiresAt:admin.firestore.Timestamp.fromMillis(1)});
 await assert.rejects(hierarchy.changeMembership('guest',{boardId:a,inviteId:'expired'},'accept','guest@example.test'));
});
test('direct + recursive totals preserve multiple currencies, snapshots, manual rates, rounding and legacy ILS',async()=>{
 const a=await create(),b=await create(a),c=await create(b,'USD'),d=await create(c,'RSD');
 await save(a,{amount:'2.00',currency:'ILS'});
 await save(b,{amount:'1.00',currency:'USD',fxMode:'manual',manualRate:'3.335'});
 await save(c,{amount:'4.00',currency:'USD'});
 await save(d,{amount:'-1.00',currency:'EUR'});
 await db.doc(`boards/${a}/transactions/legacy`).set({amount:1.235,createdAt:admin.firestore.Timestamp.now()});
 offline=true;
 const result=await hierarchy.getHierarchySummary('owner',{boardId:a,includeTransactions:true});
 assert.deepEqual(result.totals,{ILS:'6.58',USD:'4.00',RSD:'-3.34'});assert.equal(result.boardCount,4);
 assert.equal((await rows(a)).length,2);assert.equal((await rows(b))[0].conversion.source,'manual');assert.equal((await rows(d))[0].conversion.provider,'boi');
 assert.equal(result.worksheets.reduce((n,s)=>n+s.transactions.length,0),5);offline=false;
 provider='frankfurter';await save(d,{amount:'1.00',currency:'EUR'});assert.equal((await rows(d)).find(t=>t.amount==='1.00').conversion.provider,'frankfurter');
});
test('nested parents and leaves are valid transaction move/copy destinations; FX and authorization retained',async()=>{
 const a=await create(),b=await create(a),c=await create(b,'USD'),foreign=await create(null,'ILS','stranger');
 const {id}=await save(a,{amount:'1.00',currency:'USD',fxMode:'manual',manualRate:'3.335'});
 const args={sourceBoardId:a,transactionId:id,expectedRevision:1,expectedCurrencyRevision:0};
 await money.transfer('owner',{...args,destinationBoardIds:[b,c]},true);
 assert.equal((await rows(b))[0].conversion.rate,'3.335');assert.equal((await rows(c))[0].conversion,null);
 await assert.rejects(money.transfer('owner',{...args,destinationBoardId:foreign}));
 await money.transfer('owner',{...args,destinationBoardId:b});assert.equal((await rows(a)).length,0);assert.equal((await rows(b)).length,2);
});
test('non-leaf deletion blocks, leaf cleanup removes transactions, concurrent attach/delete never orphans',async()=>{
 const a=await create(),b=await create(a);await save(b);
 await assert.rejects(hierarchy.deleteBoard('owner',{boardId:a}),{code:'failed-precondition'});
 assert.equal((await read(b)).parentBoardId,a);
 await assert.rejects(hierarchy.deleteBoard('stranger',{boardId:b}),{code:'permission-denied'});
 await hierarchy.deleteBoard('owner',{boardId:b});assert.equal(await read(b),undefined);assert.equal((await rows(b)).length,0);
 const c=await create();
 await Promise.allSettled([hierarchy.deleteBoard('owner',{boardId:a}),hierarchy.reparentBoard('owner',{boardId:c,parentBoardId:a})]);
 if((await read(c)).parentBoardId===a) assert.ok(await read(a));
});
test('Firestore rejects direct hierarchy, owner, membership, tombstone, deletion and money bypasses',async()=>{
 const a=await create(),b=await create(a);const owner=rules.authenticatedContext('owner').firestore(),stranger=rules.authenticatedContext('stranger').firestore();
 for(const data of [{parentBoardId:b},{subBoardIds:[b]},{memberUids:['owner','attacker']},{directMemberUids:['attacker']},{ownerUid:'attacker'},{deleting:true},{currency:'USD'}])await assertFails(updateDoc(doc(owner,`boards/${a}`),data));
 await assertFails(deleteDoc(doc(owner,`boards/${a}`)));
 await assertFails(setDoc(doc(owner,'boards/bypass'),{title:'Bad',ownerUid:'owner',memberUids:['owner']}));
 await assertFails(setDoc(doc(owner,`boards/${a}/transactions/bypass`),{amount:'1.00'}));
 await assertFails(getDoc(doc(stranger,`boards/${b}`)));
 await assertSucceeds(updateDoc(doc(owner,`boards/${a}`),{title:'Renamed'}));
 const children=await assertSucceeds(getDocs(query(collection(owner,'boards'),where('parentBoardId','==',a),where('memberUids','array-contains','owner'))));
 assert.deepEqual(children.docs.map(d=>d.id),[b]);
});
test('failed leaf cleanup keeps a durable tombstone and retries safely',async()=>{
 const a=await create();await save(a);
 const failing=createHierarchyOperations({db:{collection:db.collection.bind(db),runTransaction:db.runTransaction.bind(db),recursiveDelete:async()=>{throw Error('injected cleanup failure');}},timestamp});
 await assert.rejects(failing.deleteBoard('owner',{boardId:a}),/injected/);
 assert.equal((await read(a)).deleting,true);assert.equal((await rows(a)).length,1);
 await assert.rejects(create(a),{code:'failed-precondition'});
 await assert.rejects(save(a),{code:'failed-precondition'});
 await hierarchy.deleteBoard('owner',{boardId:a});assert.equal(await read(a),undefined);
});
test('large atomic membership mutations fail before writing without limiting depth',async()=>{
 const a=await create(),parent=await create();const batch=db.batch();
 for(let i=0;i<450;i++)batch.set(db.collection('boards').doc(),{title:'Child',ownerUid:'owner',memberUids:['owner'],directMemberUids:['owner'],parentBoardId:a});
 await batch.commit();
 await assert.rejects(hierarchy.reparentBoard('owner',{boardId:a,parentBoardId:parent}),{code:'resource-exhausted'});
 assert.equal((await read(a)).parentBoardId,null);
});
test('concurrent invite acceptance and subtree movement preserve authoritative access',async()=>{
 const a=await create(),b=await create(a),c=await create(b),newParent=await create();
 await db.doc(`boards/${a}/invites/race`).set({invitedEmailLower:'race@example.test'});
 await Promise.all([hierarchy.changeMembership('race',{boardId:a,inviteId:'race'},'accept','race@example.test'),hierarchy.reparentBoard('owner',{boardId:b,parentBoardId:newParent})]);
 assert.ok((await read(a)).memberUids.includes('race'));assert.ok(!(await read(b)).memberUids.includes('race'));assert.ok(!(await read(c)).memberUids.includes('race'));
});
