import { TRANSACTION_TYPE_LABELS } from '../constants/transactionTypes';

const FOOTER_TEXT = "Generated by OF8's Expense Management web app";
const FOOTER_URL = 'https://of8-expense-management.web.app/';

const TEXT_FORMULA_PREFIX_RE = /^[=+\-@]/;

const COLUMNS = [
  { key: 'transactionDate', header: 'תאריך עסקה (אופציונלי)', type: 'text' },
  { key: 'essence', header: 'שם העסק', type: 'text' },
  { key: 'amount', header: 'סכום (₪)', type: 'number' },
  { key: 'type', header: 'סוג עסקה', type: 'text', map: (value) => TRANSACTION_TYPE_LABELS[value] || value || '' },
  { key: 'name', header: 'שם', type: 'text' },
  { key: 'cardLast4', header: '4 ספרות אחרונות של הכרטיס', type: 'text' },
  { key: 'installmentCurrent', header: 'תשלום נוכחי', type: 'number' },
  { key: 'installmentTotal', header: 'מתוך כמה תשלומים', type: 'number' },
  { key: 'comment', header: 'פירוט/הערות (אופציונלי)', type: 'text' },
];

function normalizeNullable(value) {
  return value == null ? '' : value;
}

function protectFormulaText(value) {
  if (typeof value !== 'string') return value;
  return TEXT_FORMULA_PREFIX_RE.test(value) ? `'${value}` : value;
}

function formatDateForExport(value) {
  const normalized = normalizeNullable(value);
  if (typeof normalized !== 'string') return normalized;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(normalized)) return protectFormulaText(normalized);

  const [year, month, day] = normalized.split('-').map(Number);
  const parsed = new Date(year, month - 1, day);
  if (
    Number.isNaN(parsed.getTime()) ||
    parsed.getFullYear() !== year ||
    parsed.getMonth() + 1 !== month ||
    parsed.getDate() !== day
  ) {
    return protectFormulaText(normalized);
  }

  return `${String(day).padStart(2, '0')}/${String(month).padStart(2, '0')}/${year}`;
}

function mapTransactionToRow(tx) {
  return COLUMNS.map((column) => {
    const rawValue = normalizeNullable(tx?.[column.key]);

    if (column.key === 'transactionDate') {
      return formatDateForExport(rawValue);
    }

    if (column.type === 'number') {
      return rawValue === '' ? '' : rawValue;
    }

    const mapped = column.map ? column.map(rawValue) : rawValue;
    const safeValue = normalizeNullable(mapped);
    return protectFormulaText(String(safeValue));
  });
}

export function sanitizeWorksheetName(name, fallback = 'Sheet') {
  const normalized = String(name || '').trim() || fallback;
  const cleaned = normalized
    .replace(/[\\/?*[\]:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  const truncated = (cleaned || fallback).slice(0, 31);
  return truncated || fallback;
}

export function sanitizeFilename(name, fallback = 'board') {
  const normalized = String(name || '').trim() || fallback;
  const withoutControlChars = [...normalized].filter((char) => char.charCodeAt(0) >= 32).join('');
  const cleaned = withoutControlChars
    .replace(/[<>:"/\\|?*]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/g, '');

  return cleaned || fallback;
}

function appendFooterRow(XLSX, worksheet, tableRowCount) {
  const spacerRowIndex = tableRowCount + 1;
  const footerRowIndex = tableRowCount + 2;

  XLSX.utils.sheet_add_aoa(
    worksheet,
    [
      [],
      [FOOTER_TEXT, FOOTER_URL],
    ],
    { origin: `A${spacerRowIndex}` },
  );

  const footerUrlCellRef = `B${footerRowIndex}`;
  if (worksheet[footerUrlCellRef]) {
    worksheet[footerUrlCellRef].l = { Target: FOOTER_URL };
  }
}

function createWorksheet(XLSX, transactions) {
  const rows = [COLUMNS.map((column) => column.header), ...transactions.map(mapTransactionToRow)];
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  appendFooterRow(XLSX, worksheet, rows.length);
  return worksheet;
}

export function exportBoardToExcel({ boardName, worksheets }) {
  const XLSX = window.XLSX;
  if (!XLSX?.utils?.book_new || !XLSX?.writeFile) {
    throw new Error('ספריית הייצוא לא נטענה. רענן את העמוד ונסה שוב.');
  }

  const workbook = XLSX.utils.book_new();
  const usedSheetNames = new Set();

  worksheets.forEach(({ name, transactions }) => {
    const baseSheetName = sanitizeWorksheetName(name, 'Sheet');
    let sheetName = baseSheetName;
    let suffix = 1;
    while (usedSheetNames.has(sheetName)) {
      const candidate = `${baseSheetName.slice(0, 28)}_${suffix}`;
      sheetName = sanitizeWorksheetName(candidate, `Sheet_${suffix}`);
      suffix += 1;
    }
    usedSheetNames.add(sheetName);

    const worksheet = createWorksheet(XLSX, transactions || []);
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  });

  const safeFilename = `${sanitizeFilename(boardName, 'board')}.xlsx`;
  XLSX.writeFile(workbook, safeFilename);
}
