import { TRANSACTION_TYPE_LABELS } from '../constants/transactionTypes';

const FOOTER_TEXT = "Generated by OF8's Expense Management web app - https://of8-expense-management.web.app/";
const FOOTER_URL = 'https://of8-expense-management.web.app/';
const TEXT_FORMULA_PREFIX_RE = /^[=+\-@]/;

const COLUMNS = [
  { key: 'transactionDate', header: 'תאריך עסקה (אופציונלי)', type: 'date', width: 16, alignment: 'center' },
  { key: 'essence', header: 'שם העסק', type: 'text', width: 28, wrapText: true },
  { key: 'amount', header: 'סכום (₪)', type: 'number', width: 14, alignment: 'right' },
  {
    key: 'type',
    header: 'סוג עסקה',
    type: 'text',
    width: 18,
    map: (value) => TRANSACTION_TYPE_LABELS[value] || value || '',
  },
  { key: 'name', header: 'שם', type: 'text', width: 20 },
  { key: 'cardLast4', header: '4 ספרות אחרונות של הכרטיס', type: 'text', width: 20, alignment: 'center' },
  { key: 'installmentCurrent', header: 'תשלום נוכחי', type: 'number', width: 14, alignment: 'center' },
  { key: 'installmentTotal', header: 'מתוך כמה תשלומים', type: 'number', width: 16, alignment: 'center' },
  { key: 'comment', header: 'פירוט/הערות (אופציונלי)', type: 'text', width: 42, wrapText: true },
];

const TABLE_BORDER = {
  top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
  left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
  bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
  right: { style: 'thin', color: { argb: 'FFE5E7EB' } },
};

function normalizeNullableValue(value) {
  return value == null ? '' : value;
}

function escapeExcelFormulaText(value) {
  if (typeof value !== 'string') return value;
  return TEXT_FORMULA_PREFIX_RE.test(value) ? `'${value}` : value;
}

function parseDateValue(value) {
  const normalized = normalizeNullableValue(value);
  if (normalized === '') return null;
  if (normalized instanceof Date && !Number.isNaN(normalized.getTime())) {
    return normalized;
  }

  if (typeof normalized !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(normalized)) {
    return null;
  }

  const [year, month, day] = normalized.split('-').map(Number);
  const parsed = new Date(year, month - 1, day);
  if (
    Number.isNaN(parsed.getTime()) ||
    parsed.getFullYear() !== year ||
    parsed.getMonth() + 1 !== month ||
    parsed.getDate() !== day
  ) {
    return null;
  }

  return parsed;
}

function mapTransactionToExportRow(tx) {
  return COLUMNS.map((column) => {
    const rawValue = normalizeNullableValue(tx?.[column.key]);

    if (column.type === 'date') {
      const parsedDate = parseDateValue(rawValue);
      if (parsedDate) return parsedDate;

      const fallbackDateText = normalizeNullableValue(rawValue);
      return fallbackDateText === '' ? '' : escapeExcelFormulaText(String(fallbackDateText));
    }

    if (column.type === 'number') {
      if (rawValue === '') return '';
      const parsed = Number(rawValue);
      return Number.isFinite(parsed) ? parsed : '';
    }

    const mapped = column.map ? column.map(rawValue) : rawValue;
    const safeValue = normalizeNullableValue(mapped);
    return safeValue === '' ? '' : escapeExcelFormulaText(String(safeValue));
  });
}

export function sanitizeWorksheetName(name, fallback = 'Sheet') {
  const normalized = String(name || '').trim() || fallback;
  const cleaned = normalized
    .replace(/[\\/?*[\]:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  const truncated = (cleaned || fallback).slice(0, 31);
  return truncated || fallback;
}

export function sanitizeFilename(name, fallback = 'board') {
  const normalized = String(name || '').trim() || fallback;
  const withoutControlChars = [...normalized].filter((char) => char.charCodeAt(0) >= 32).join('');
  const cleaned = withoutControlChars
    .replace(/[<>:"/\\|?*]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/g, '');

  return cleaned || fallback;
}

function getColumnWidth(column, rows, columnIndex) {
  const contentMax = rows.reduce((max, row) => {
    const value = row[columnIndex];
    if (value == null || value === '') return max;
    if (value instanceof Date) return Math.max(max, 10);
    return Math.max(max, String(value).length);
  }, column.header.length);

  const min = 12;
  const max = column.wrapText ? 48 : 32;
  return Math.min(max, Math.max(min, Math.max(column.width || min, contentMax + 2)));
}

function applyWorksheetStyling(worksheet, dataRows) {
  const lastCol = COLUMNS.length;
  worksheet.columns = COLUMNS.map((column, idx) => ({
    key: column.key,
    width: getColumnWidth(column, dataRows, idx),
  }));

  worksheet.views = [{ state: 'frozen', ySplit: 1, rightToLeft: true }];
  worksheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: lastCol },
  };

  const headerRow = worksheet.getRow(1);
  headerRow.height = 30;

  for (let col = 1; col <= lastCol; col += 1) {
    const headerCell = worksheet.getCell(1, col);
    headerCell.font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
    headerCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } };
    headerCell.border = TABLE_BORDER;
    headerCell.alignment = { vertical: 'middle', horizontal: 'right', wrapText: true };
  }

  dataRows.forEach((_, idx) => {
    const rowNumber = idx + 2;
    const row = worksheet.getRow(rowNumber);
    const isStripedRow = idx % 2 === 1;

    row.eachCell({ includeEmpty: true }, (cell, colNumber) => {
      const column = COLUMNS[colNumber - 1];
      const horizontal = column.alignment || (column.type === 'number' ? 'right' : 'right');

      cell.border = TABLE_BORDER;
      cell.alignment = {
        vertical: 'middle',
        horizontal,
        wrapText: Boolean(column.wrapText),
      };

      if (column.type === 'number' && cell.value !== '') {
        cell.numFmt = '#,##0.00';
      }

      if (column.type === 'date' && cell.value instanceof Date) {
        cell.numFmt = 'dd/mm/yyyy';
      }

      if (isStripedRow) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      }
    });
  });
}

function appendFooterRow(worksheet) {
  const spacerRow = worksheet.addRow([]);
  spacerRow.height = 8;

  const footerRow = worksheet.addRow([
    {
      text: FOOTER_TEXT,
      hyperlink: FOOTER_URL,
    },
  ]);

  const footerRowNumber = footerRow.number;
  worksheet.mergeCells(footerRowNumber, 1, footerRowNumber, COLUMNS.length);

  const footerCell = worksheet.getCell(footerRowNumber, 1);
  footerCell.font = {
    size: 10,
    color: { argb: 'FF64748B' },
    underline: true,
  };
  footerCell.alignment = { horizontal: 'center', vertical: 'middle' };
  footerCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
  footerCell.border = TABLE_BORDER;

  footerRow.height = 20;
}

function addWorksheet(workbook, usedSheetNames, name, transactions = []) {
  const baseSheetName = sanitizeWorksheetName(name, 'Sheet');
  let sheetName = baseSheetName;
  let suffix = 1;

  while (usedSheetNames.has(sheetName)) {
    const suffixText = `_${suffix}`;
    const maxBaseLength = Math.max(0, 31 - suffixText.length);
    const candidate = `${baseSheetName.slice(0, maxBaseLength)}${suffixText}`;
    sheetName = sanitizeWorksheetName(candidate, `Sheet${suffixText}`);
    suffix += 1;
  }

  usedSheetNames.add(sheetName);

  const worksheet = workbook.addWorksheet(sheetName);
  const dataRows = transactions.map(mapTransactionToExportRow);

  worksheet.addRow(COLUMNS.map((column) => column.header));
  dataRows.forEach((row) => worksheet.addRow(row));

  applyWorksheetStyling(worksheet, dataRows);
  appendFooterRow(worksheet);
}

function buildSummarySheet(workbook, usedSheetNames, worksheets) {
  if (worksheets.length === 0) return;

  const summaryColumns = [
    { header: 'לוח משנה', width: 28 },
    { header: 'כמות עסקאות', width: 14 },
    { header: 'סה"כ חיובי', width: 14 },
    { header: 'סה"כ שלילי', width: 14 },
    { header: 'נטו', width: 14 },
  ];

  const sheetName = (() => {
    const base = sanitizeWorksheetName('סיכום', 'Summary');
    if (!usedSheetNames.has(base)) {
      usedSheetNames.add(base);
      return base;
    }
    let suffix = 1;
    while (usedSheetNames.has(`${base}_${suffix}`)) suffix += 1;
    const candidate = sanitizeWorksheetName(`${base}_${suffix}`, 'Summary');
    usedSheetNames.add(candidate);
    return candidate;
  })();

  const worksheet = workbook.addWorksheet(sheetName);
  worksheet.columns = summaryColumns;
  worksheet.views = [{ state: 'frozen', ySplit: 1, rightToLeft: true }];

  worksheets.forEach(({ name, transactions = [] }) => {
    const stats = transactions.reduce(
      (acc, tx) => {
        const amount = Number(tx?.amount);
        if (!Number.isFinite(amount)) return acc;
        if (amount > 0) acc.positive += amount;
        if (amount < 0) acc.negative += amount;
        acc.net += amount;
        return acc;
      },
      { positive: 0, negative: 0, net: 0 },
    );

    worksheet.addRow([
      escapeExcelFormulaText(String(normalizeNullableValue(name))),
      transactions.length,
      stats.positive,
      stats.negative,
      stats.net,
    ]);
  });

  const rowCount = worksheet.rowCount;
  worksheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: summaryColumns.length },
  };

  const headerRow = worksheet.getRow(1);
  headerRow.height = 30;

  for (let col = 1; col <= summaryColumns.length; col += 1) {
    const headerCell = worksheet.getCell(1, col);
    headerCell.font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
    headerCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F766E' } };
    headerCell.border = TABLE_BORDER;
    headerCell.alignment = { vertical: 'middle', horizontal: 'right' };
  }

  for (let rowNum = 2; rowNum <= rowCount; rowNum += 1) {
    for (let col = 1; col <= summaryColumns.length; col += 1) {
      const cell = worksheet.getCell(rowNum, col);
      cell.border = TABLE_BORDER;
      const isNumeric = col > 1;
      cell.alignment = { vertical: 'middle', horizontal: isNumeric ? 'right' : 'right' };
      if (isNumeric) {
        cell.numFmt = col === 2 ? '0' : '#,##0.00';
      }
      if (rowNum % 2 === 1) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      }
    }
  }

  appendFooterRow(worksheet);
}

function triggerWorkbookDownload(buffer, filename) {
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

export async function exportBoardToExcel({ boardName, worksheets, includeSummarySheet = false }) {
  const ExcelJS = window.ExcelJS;
  if (!ExcelJS?.Workbook) {
    throw new Error('ספריית הייצוא לא נטענה. רענן את העמוד ונסה שוב.');
  }

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'OF8 Expense Management';
  workbook.created = new Date();

  const usedSheetNames = new Set();
  const normalizedWorksheets = worksheets.map((worksheet) => ({
    ...worksheet,
    transactions: worksheet.transactions || [],
  }));

  if (includeSummarySheet) {
    buildSummarySheet(workbook, usedSheetNames, normalizedWorksheets);
  }

  normalizedWorksheets.forEach(({ name, transactions }) => {
    addWorksheet(workbook, usedSheetNames, name, transactions);
  });

  const safeFilename = `${sanitizeFilename(boardName, 'board')}.xlsx`;
  const buffer = await workbook.xlsx.writeBuffer();
  triggerWorkbookDownload(buffer, safeFilename);
}
